version: "3.8"
services:
  nginx:
    image: nginx:1.25.2
    container_name: laravel_nginx
    volumes:
      - ./src:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports: # ホスト側:コンテナ側 でポートを接続する
      - 8080:80
    depends_on:
      - php

  php:
    container_name: laravel_php
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www
    ports:
      - "9001:9000"
      - "6002:6001"